//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mr.brand_store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CId { get; set; }
        public int Pid { get; set; }
        public int Uid { get; set; }
        public string quantity { get; set; }
    
        public virtual user user { get; set; }
        public virtual Product Product { get; set; }
    }
}
