//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mr.brand_store.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    public partial class Product
    {
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Name of Product is required")]
        public string name { get; set; }
        //[Required(ErrorMessage = "Pleease Select one file to upload")]
        public string path { get; set; }
        [Required(ErrorMessage = "Price of Product is required")]
        public string type { get; set; }
        [Required(ErrorMessage = "Price of Product is required")]
    
        public double price { get; set; }
        public int rating { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
